#!/usr/bin/env node
/**
 * QAIP Report Writer — Setup Script
 * Run: node scripts/setup.js
 */

const fs       = require('fs');
const path     = require('path');
const readline = require('readline');

const ROOT    = path.join(__dirname, '..');
const ENV     = path.join(ROOT, '.env');
const EXAMPLE = path.join(ROOT, '.env.example');

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise(resolve => rl.question(q, resolve));

async function main() {
  console.log('\n╔══════════════════════════════════════════════╗');
  console.log('║     QAIP Report Writer — Setup Wizard        ║');
  console.log('╚══════════════════════════════════════════════╝\n');

  // Check .env already exists
  if (fs.existsSync(ENV)) {
    const overwrite = await ask('  .env already exists. Overwrite? (y/N): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('\n  ✓ Keeping existing .env. Run "npm start" to launch.\n');
      rl.close(); return;
    }
  }

  // Get API key
  console.log('  Get your Anthropic API key from: https://console.anthropic.com/\n');
  let apiKey = '';
  while (!apiKey.startsWith('sk-ant-')) {
    apiKey = await ask('  Paste your Anthropic API key: ');
    apiKey = apiKey.trim();
    if (!apiKey.startsWith('sk-ant-')) {
      console.log('  ⚠  Key should start with sk-ant-  — try again.\n');
    }
  }

  // Get port
  const portInput = await ask('  Server port [3000]: ');
  const port = portInput.trim() || '3000';

  // Get host
  console.log('\n  Host binding:');
  console.log('    1) localhost  — only this machine (development)');
  console.log('    2) 0.0.0.0   — all network interfaces (office/server use)');
  const hostChoice = await ask('  Choose [1]: ');
  const host = hostChoice.trim() === '2' ? '0.0.0.0' : 'localhost';

  // Write .env
  const envContent = [
    '# QAIP Report Writer — Environment (auto-generated by setup.js)',
    `ANTHROPIC_API_KEY=${apiKey}`,
    `PORT=${port}`,
    `HOST=${host}`,
  ].join('\n') + '\n';

  fs.writeFileSync(ENV, envContent);

  console.log('\n  ✓ .env created');
  console.log(`  ✓ API key: ${apiKey.slice(0,8)}…${apiKey.slice(-4)}`);
  console.log(`  ✓ Server : http://${host === '0.0.0.0' ? 'YOUR_IP' : 'localhost'}:${port}`);
  console.log('\n  Next steps:');
  console.log('    npm install     ← install dependencies');
  console.log('    npm start       ← launch the app');
  console.log('    npm run dev     ← launch with auto-reload (development)\n');

  rl.close();
}

main().catch(err => { console.error(err); process.exit(1); });
